linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - vet
    - unused
    - misspell
    - revive
  disable:
    - errcheck

issues:
  include:
    - EXC0002

run:
  timeout: 2m
