name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: Project Checks
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/aufs
          fetch-depth: 25

      - uses: containerd/project-checks@v1
        with:
          working-directory: src/github.com/containerd/aufs

  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/aufs

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          working-directory: src/github.com/containerd/aufs

  tests:
    name: Tests
    # Canonical has dropped AUFS support starting Ubuntu 21.04.
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/aufs

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.txt -test.root -exec "sudo -n"  ./...
          bash <(curl -s https://codecov.io/bash)
        working-directory: src/github.com/containerd/aufs
